connect:
  #build: connect
  image: anvilresearch/connect
  links:
    - redis
  volumes:
    - ./connect/config:/opt/connect/config:ro
    - ./connect/views:/opt/connect/views:ro
  ports:
    - "3000:3000"
  restart: always

nginx:
  #build: nginx
  image: anvilresearch/nginx
  links:
    - connect
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d:ro
    - ./nginx/certs:/etc/nginx/certs:ro
    - ./connect/public:/var/www/html:ro
    - ./nginx/logs:/var/log/nginx
  ports:
    - "443:443"
  restart: always

redis:
  #build: redis
  image: anvilresearch/redis
  volumes:
    - ./redis/data:/data
  ports:
    - "6379:6379"
  restart: always
